version: 1.0.{build}

# clone directory
clone_folder: C:\MuseScore

# set clone depth
clone_depth: 50                      # clone entire repository history if not defined

image: Visual Studio 2019

branches:
    only:
    - master

install:
  - docker version

build_script:
  - cmd: docker run -i -v "%cd%:C:\MuseScore" "igorkorsukov/musescore:windows_qt5151_x86-64_latest" C:\MuseScore\build\docker\windows\build.bat
