name: CI_Linux

on:
  pull_request:
    branches:
    - master_off

jobs:
  linux_build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 3
    - name: get commit message
      run: |
         export commitmsg="$(git log --format=%B -n 1 --skip 1 | head -1)"
         echo "::set-env name=commitmsg::${commitmsg}"
    - name: Build
      run: |
        sudo docker run -i -v "${PWD}:/MuseScore" "igorkorsukov/musescore:linux_appimage_qt5150_x86-64_latest" /MuseScore/build/docker/linux/build.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: MuseScore-x86_64.AppImage
        path: ./build.release/MuseScore-x86_64.AppImage
