name: CI_Linux

on:
  pull_request:
    branches:
    - my/3.x

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    # - name: Cancel Previous Runs
    #   uses: styfle/cancel-workflow-action@0.5.0
    #   with:
    #     access_token: ${{ github.token }}
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 3
    - name: Setup environment
      run: |
        sudo bash ./build/ci/linux/setup.sh
    - name: Build
      run: |
        sudo bash ./build/ci/linux/build.sh ${{ secrets.TELEMETRY_TRACK_ID }}
    - name: Package 
      run: |
        sudo bash ./build/ci/linux/package.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: MuseScore-x86_64.AppImage
        path: ./build.artifacts/
    - name: Publish package
      run: |
        sudo bash ./build/ci/linux/publish.sh ${{ secrets.OSUOSL_SSH_ENCRYPT_SECRET }} 
