name: CI_MacOS

on:
  pull_request:
    branches:
    - master_off

env:
    DEVELOPER_DIR: /Applications/Xcode_10.3.app/Contents/Developer

jobs:
  cancel_previous:
    runs-on: ubuntu-18.04
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.5.0
      with:
        access_token: ${{ github.token }}
  build:    
    runs-on: macos-10.15
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 3
    - name: Test coding style
      run: |
        sudo bash ./build/ci/macos/checkcodestyle.sh  
    - name: Setup environment
      run: |
        sudo bash ./build/ci/macos/setup.sh
    - name: Build          
      run: |
        bash ./build/ci/macos/build.sh           
    - name: Package 
      run: |
        bash ./build/ci/macos/package.sh  
    - name: Upload 
      uses: actions/upload-artifact@v1
      with:
        name: MuseScoreNightly-PR.dmg
        path: ./applebuild/MuseScoreNightly-PR.dmg