name: CI_Windows

on:
  pull_request:
    branches:
    - master

jobs:
  windows_build:
    runs-on: windows-2019
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 3
    - name: Setup environment
      run: |
         build\ci\windows\setup.bat
    - name: Build
      run: |
         build\ci\windows\build.bat
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: MuseScore_x86-64.7z
        path: MuseScore_x86-64.7z
