name: CI_Windows

on:
  pull_request:
    branches:
    - my/3.x

env:
  MU_BUILD_CONFIG: stable
jobs:
  build:
    runs-on: windows-2019
    steps:
    # - name: Cancel Previous Runs
    #   uses: styfle/cancel-workflow-action@0.5.0
    #   with:
    #     access_token: ${{ github.token }}
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 3
    - name: Fetch submodules
      run: |
        git submodule update --init --recursive
    # - name: Setup environment
    #   run: |
    #     build\ci\windows\setup.bat
    # - name: Build
    #   run: |
    #     build\ci\windows\build.bat ${{ secrets.TELEMETRY_TRACK_ID }} ${{ secrets.CRASH_LOG_SERVER_URL }}
    - name: Package 
      run: |      
        build\ci\windows\test\package.bat %MU_BUILD_CONFIG% ${{ secrets.WIN_SIGN_CERTIFICATE_ENCRYPT_SECRET }} ${{ secrets.WIN_SIGN_CERTIFICATE_PASSWORD }}
        echo "[wf] after pack ARTIFACT_NAME: %ARTIFACT_NAME%"
        echo "::set-env name=MU_ARTIFACT_NAME::%ARTIFACT_NAME%"
      shell: cmd
    # - name: Upload artifact on GitHub
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: MuseScore
    #     path: artefacts\
    - name: Publish package
      run: |
        echo "[wf] befor pub ARTIFACT_NAME: %MU_ARTIFACT_NAME%"
        build\ci\windows\publish.bat %MU_ARTIFACT_NAME% ${{ secrets.OSUOSL_SSH_ENCRYPT_SECRET }} 
      shell: cmd   
